server:
  port: 1010

spring:
  application:
    name: nci_web_client
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5431/nci_web_client
    password: 'root123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: 'true'