server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5431/fraud
    password: 'root123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: 'true'
